In [15]:
import requests
from bs4 import BeautifulSoup

In [16]:
url = 'https://ajuntament.barcelona.cat/estadistica/castella/Estadistiques_per_temes/Poblacio_i_demografia/Demografia/Defuncions/a2018/t12.htm'
res = requests.get(url).text
html = BeautifulSoup(res)

In [17]:
table = html.select('table')[0]

In [18]:
column = [e.get_text(strip=True) for e in table.select("td.WhadsColVar1")]
column

['Distritos', 'TOTAL', 'Hombres', 'Mujeres']

In [19]:
data = [[e.get_text(strip=True) for e in row.select('td')] for row in table.select("tr:nth-of-type(1n+2)")]
data

[[''],
 ['2.\xa0Distritos'],
 [''],
 ['Distritos', 'TOTAL', 'Hombres', 'Mujeres'],
 [''],
 ['', '', '', ''],
 ['BARCELONA', '15.238', '7.161', '8.077'],
 ['', '', '', ''],
 ['1.Ciutat Vella', '708', '347', '361'],
 ['2.Eixample', '2.669', '1.132', '1.537'],
 ['3.Sants-Montjuïc', '1.648', '800', '848'],
 ['4.Les Corts', '763', '357', '406'],
 ['5.Sarrià-Sant Gervasi', '1.394', '608', '786'],
 ['6.Gràcia', '1.183', '538', '645'],
 ['7.Horta-Guinardó', '1.876', '895', '981'],
 ['8.Nou Barris', '1.719', '874', '845'],
 ['9.Sant Andreu', '1.269', '627', '642'],
 ['10.Sant Martí', '2.009', '983', '1.026'],
 [''],
 [''],
 ["Fuente: Ajuntament de Barcelona. Departament d'Estadística i Difusió de Dades. Movimientos demográficos 2018."],
 ['']]

In [20]:
for i in range(len(data)):
    if not data[i][0].isnumeric():
        data[i].insert(0, data[i-1][0])
data = data[8:18]
data

[['', '1.Ciutat Vella', '708', '347', '361'],
 ['', '2.Eixample', '2.669', '1.132', '1.537'],
 ['', '3.Sants-Montjuïc', '1.648', '800', '848'],
 ['', '4.Les Corts', '763', '357', '406'],
 ['', '5.Sarrià-Sant Gervasi', '1.394', '608', '786'],
 ['', '6.Gràcia', '1.183', '538', '645'],
 ['', '7.Horta-Guinardó', '1.876', '895', '981'],
 ['', '8.Nou Barris', '1.719', '874', '845'],
 ['', '9.Sant Andreu', '1.269', '627', '642'],
 ['', '10.Sant Martí', '2.009', '983', '1.026']]

In [21]:
for i in data:
    i.pop(0)
data

[['1.Ciutat Vella', '708', '347', '361'],
 ['2.Eixample', '2.669', '1.132', '1.537'],
 ['3.Sants-Montjuïc', '1.648', '800', '848'],
 ['4.Les Corts', '763', '357', '406'],
 ['5.Sarrià-Sant Gervasi', '1.394', '608', '786'],
 ['6.Gràcia', '1.183', '538', '645'],
 ['7.Horta-Guinardó', '1.876', '895', '981'],
 ['8.Nou Barris', '1.719', '874', '845'],
 ['9.Sant Andreu', '1.269', '627', '642'],
 ['10.Sant Martí', '2.009', '983', '1.026']]

In [22]:
import pandas as pd

death_by_district_18 = pd.DataFrame(data,columns=column)
death_by_district_18

               Distritos  TOTAL Hombres Mujeres
0         1.Ciutat Vella    708     347     361
1             2.Eixample  2.669   1.132   1.537
2       3.Sants-Montjuïc  1.648     800     848
3            4.Les Corts    763     357     406
4  5.Sarrià-Sant Gervasi  1.394     608     786
5               6.Gràcia  1.183     538     645
6       7.Horta-Guinardó  1.876     895     981
7           8.Nou Barris  1.719     874     845
8          9.Sant Andreu  1.269     627     642
9          10.Sant Martí  2.009     983   1.026

In [23]:
#Districts names are replaced by the name of the nearest weather station

death_by_district_18 = death_by_district_18.replace('1.Ciutat Vella','Barcelona - Ciutadella')
death_by_district_18 = death_by_district_18.replace('4.Les Corts','Barcelona - Palau Reial')
death_by_district_18 = death_by_district_18.replace('2.Eixample','Barcelona - Eixample')
death_by_district_18 = death_by_district_18.replace('3.Sants-Montjuïc','Barcelona - Sants')
death_by_district_18 = death_by_district_18.replace('5.Sarrià-Sant Gervasi','Barcelona - Observ Fabra')
death_by_district_18 = death_by_district_18.replace('6.Gràcia','Barcelona - Gràcia')
death_by_district_18 = death_by_district_18.replace('7.Horta-Guinardó','Barcelona - Vall Hebron')
death_by_district_18 = death_by_district_18.replace('8.Nou Barris','Barcelona - Vall Hebron')
death_by_district_18 = death_by_district_18.replace('9.Sant Andreu','Barcelona - Poblenou')
death_by_district_18 = death_by_district_18.replace('10.Sant Martí','Barcelona - Poblenou')

death_by_district_18

                  Distritos  TOTAL Hombres Mujeres
0    Barcelona - Ciutadella    708     347     361
1      Barcelona - Eixample  2.669   1.132   1.537
2         Barcelona - Sants  1.648     800     848
3   Barcelona - Palau Reial    763     357     406
4  Barcelona - Observ Fabra  1.394     608     786
5        Barcelona - Gràcia  1.183     538     645
6   Barcelona - Vall Hebron  1.876     895     981
7   Barcelona - Vall Hebron  1.719     874     845
8      Barcelona - Poblenou  1.269     627     642
9      Barcelona - Poblenou  2.009     983   1.026

In [24]:
#Rows with repeated names are eliminated and their values are averaged
death_by_district_18=death_by_district_18.drop([7,8], axis=0)
death_by_district_18

                  Distritos  TOTAL Hombres Mujeres
0    Barcelona - Ciutadella    708     347     361
1      Barcelona - Eixample  2.669   1.132   1.537
2         Barcelona - Sants  1.648     800     848
3   Barcelona - Palau Reial    763     357     406
4  Barcelona - Observ Fabra  1.394     608     786
5        Barcelona - Gràcia  1.183     538     645
6   Barcelona - Vall Hebron  1.876     895     981
9      Barcelona - Poblenou  2.009     983   1.026

In [25]:
death_by_district_18=death_by_district_18.replace('1.876','1798').replace('895','885').replace('981','913').replace('2.009','1639').replace('983','805').replace('1.026','834').replace('2.669','2669').replace('1.648','1648').replace('1.394','1394').replace('1.183','1183').replace('1.132','1132').replace('1.537','1537')
death_by_district_18

                  Distritos TOTAL Hombres Mujeres
0    Barcelona - Ciutadella   708     347     361
1      Barcelona - Eixample  2669    1132    1537
2         Barcelona - Sants  1648     800     848
3   Barcelona - Palau Reial   763     357     406
4  Barcelona - Observ Fabra  1394     608     786
5        Barcelona - Gràcia  1183     538     645
6   Barcelona - Vall Hebron  1798     885     913
9      Barcelona - Poblenou  1639     805     834

In [26]:
death_by_district_18.to_csv('death_by_district_18.csv', header=True, index=False)